BabyTimeApp/babytime_api/config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # 

  root "welcome#index"
  resources :welcome
  resources :diapers, only: [:new, :create, :destroy, :edit, :update, :show]
  resources :sleeps, only: [:new, :create, :destroy, :edit, :update, :show]
  resources :formulas, only: [:new, :create, :destroy, :edit, :update, :show]
  resources :activities
  resource :session, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create] do
    
  end
  resources :babies 

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :activities, only: [:index, :create, :show]
      resource :session, only:[:create, :destroy]
      resources :sleeps, only: [:new, :create, :destroy, :edit, :update, :show]
      resources :diapers, only: [:new, :create, :destroy, :edit, :update, :show]
      resources :formulas, only: [:new, :create, :destroy, :edit, :update, :show]
      resources :users, only: [:create] do
        #get('users/current', {to: 'users#current})
        #default url will be api/v1/users/:id/current
        get :current, on: :collection
      end
      resources :babies 
    end
  end
end

BabyTimeApp/babytime_api/app/models/baby.rb
class Baby < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: {message: "Must Enter First Name"}
  validates :last_name, presence: {message: "Must Enter Last Name"}
  validates :dob, presence: {message: "Must Enter Birth Date"}
end

BabyTimeApp/babytime_api/app/controllers/api/v1/babies_controller.rb
class Api::V1::BabiesController < Api::ApplicationController
    before_action :authenticate_user!

    def index
        baby = Baby.find_by_user_id(current_user)
        if baby
            render(json: baby)
        else
            render(json: {no: "no"})
        end
    end


    def create
        baby = Baby.new params.require(:baby)
        .permit(
          :first_name,
          :last_name,
          :dob
        )
        baby.user = current_user
        if baby.save
            render json: {id: baby.id}
        else
            render(
                json: {errors: baby.errors.messages },
                status: 422 
            )
        end
    end

    def show
        baby = Baby.find params[:id]
            if baby.user === current_user
            render(json: baby)
            
            else 
                render(json: {no: "no"})
            
            end
    end


    def update
        baby = Baby.find params[:id]
        if baby.update(baby_params)
            render json: {id: baby.id}
           
        else
            render(
                json: { errors: baby.errors.messages},
                status: 422
            )
        end

        def destroy
            baby = Baby.find params[:id]
            if baby.destroy
            
                render(
                    json:{status: 200}
                )
            else
                render( json: {status:500})
            end

        end
    end

    private
    def baby_params
        params.require(:baby).permit(:first_name,:last_name,:dob)
      end
end

BabyTimeApp/babytime_api/app/controllers/babies_controller.rb
class BabiesController < ApplicationController
    before_action :authenticate_user!

    def index
        @baby = Baby.find_by_user_id(@current_user)
    end

    def new
        @baby = Baby.new
    end

    def create
        @baby = Baby.new params.require(:baby)
        .permit(
          :first_name,
          :last_name,
          :dob
        )
        @baby.user = current_user
        if @baby.save
            flash[:success] = "Answer successfully created"
             redirect_to @baby
        end
    end

    def show
        @baby = Baby.find params[:id]
            if @baby.user != @current_user
                redirect_to activities_path
            end
    end


    def edit
        @baby = Baby.find params[:id]
        if @baby.user != @current_user
            redirect_to activities_path
        end
    end

    def update
        @baby = Baby.find params[:id]
        if @baby.update(baby_params)
            flash[:success] = "Question successfully updated"
            redirect_to @baby
            # redirect_to question_path(@question)
            # ^^older syntax
          else
            flash[:error] = "Something went wrong"
            render :edit, status: 303 
        end
    end

    private
    def baby_params
        params.require(:baby).permit(:first_name,:last_name,:dob)
      end
    
end

BabyTimeApp/babytime_api/app/helpers/babies_helper.rb
module BabiesHelper
end

BabyTimeApp/babytime_api/app/views/babies/edit.html.erb
<%= form_with(model: @baby) do |form| %>
  <div>
    <%= form.label :first_name %>
    <br>
    <%= form.text_field :first_name %>
  </div>
  <div>
    <%= form.label :last_name %>
    <br>
    <%= form.text_field :last_name%>
  </div>
  <div>
    <%= form.label :dob %>
    <br>
    <%= form.date_field :dob%>
  </div>
  <%= form.submit %>
<% end %>

BabyTimeApp/babytime_api/app/views/babies/index.html.erb
 <%if @baby%>
  <div>
    <h2> <%= link_to @baby.first_name + " " + @baby.last_name, @baby %> </h2>
    <hr>
  </div>
<%else%>
  <%= link_to "Create Baby Profile", new_baby_path%>
<% end %>

BabyTimeApp/babytime_api/app/views/babies/new.html.erb
<%= form_with(model: @baby) do |form| %>
  <div>
    <%= form.label :first_name %>
    <br>
    <%= form.text_field :first_name %>
  </div>
  <div>
    <%= form.label :last_name %>
    <br>
    <%= form.text_field :last_name%>
  </div>
  <div>
    <%= form.label :dob %>
    <br>
    <%= form.date_field :dob%>
  </div>
  <%= form.submit %>
<% end %>

BabyTimeApp/babytime_api/app/views/babies/show.html.erb
<h2><%= @baby.first_name %> </h2>
<h2><%= @baby.last_name %> </h2>
<h2><%= @baby.dob %> </h2>
<%= button_to 'Edit', edit_baby_path(@baby), method: :get %>